logging.level.org.springframework=INFO
logging.level.com.example.bogdan=DEBUG

# Cache configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=24h

# Enable cache statistics
management.endpoints.web.exposure.include=caches